# Generated by Django 3.2.14 on 2022-10-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('subs_detail', models.BooleanField(default=False)),
            ],
        ),
    ]
